[package]
name = "whot-abi"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7.0.17"
linera-sdk = "0.15.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[lib]
crate-type = ["rlib"]
